# Generated by Django 6.1.1 on 2026-09-18 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_bookmark"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="edited_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
